### ISSUE TITLE
Respecta design-ul :) Person trebuia sa fie interface nu Human :) 

### ISSUE THREAD

**Issue by benn876** [alexandrutoma6/beta-curs-8-homework#5]
https://github.com/alexandrutoma6/beta-curs-8-homework/blob/4fa4bab23da83fc270ef8a12a0dfee258025039f/src/org/beta/curs8/homework/ex2/models/Person.java#L8

**Comment by alexandrutoma6** [comment]
Yep, am vrut sa adaug in plus inca un layer
